// Generated by scripts/run.py. Numbers match metrics.json. Do not hand-edit.

export const ILLUSTRATIVE = false

export const PROTOCOL = {
  classes: ["gazelle", "zebra", "wildebeest"],
  trainSites: ["B", "C", "D", "E"],
  testSite: "Q",
  nClasses: 3,
  imgSize: 32,
  sslEpochs: 10,
  floorPct: 85,
}

export const METRICS = {
  successPct: 100.0,
  probePct: 100.0,
  sameSitePct: 98.95833333333334,
  supervisedPct: 100.0,
  randomEncoderPct: 97.5,
  chancePct: 33.333333333333336,
  nSitesTrain: 4,
  nSitesTest: 1,
  nTrain: 480,
  nTest: 120,
  nClasses: 3,
}

export const ABLATION = [
  { model: 'ssl_probe', label: 'SSL + linear probe', heldOut: 100.0, sameSite: 98.95833333333334 },
  { model: 'supervised', label: 'Supervised from scratch', heldOut: 100.0, sameSite: 98.95833333333334 },
  { model: 'random', label: 'Frozen random encoder', heldOut: 97.5, sameSite: 33.333333333333336 },
  { model: 'chance', label: 'Chance', heldOut: 33.333333333333336, sameSite: 33.333333333333336 },
]

export const PIPELINE = [
  { id: 'img', label: 'Unlabeled frames', sub: 'train-site cameras' },
  { id: 'ssl', label: 'Rotation pretext', sub: 'tiny CNN, 4-way RotNet' },
  { id: 'freeze', label: 'Freeze', sub: 'weights locked' },
  { id: 'probe', label: 'Linear probe', sub: 'train-site labels only' },
  { id: 'test', label: 'Held-out site', sub: 'new camera, same species' },
]
